begin;
select plan(42);

select has_function('public','update_my_profile',array['text','text','text','boolean','integer'],'profile patch RPC exists');
select function_privs_are('public','update_my_profile',array['text','text','text','boolean','integer'],'authenticated',array['EXECUTE'],'profile RPC is narrowly granted');
select table_privs_are('public','profiles','authenticated',array['SELECT'],'profiles has no direct update grant');
select function_privs_are('public','get_current_budget',array[]::text[],'authenticated',array['EXECUTE'],'budget aggregate is granted');
select function_privs_are('public','get_financial_summary',array[]::text[],'authenticated',array['EXECUTE'],'summary aggregate is granted');
select function_privs_are('public','get_analytics_overview',array[]::text[],'authenticated',array['EXECUTE'],'analytics aggregate is granted');
select function_privs_are('public','create_money_transaction',array['uuid','transaction_type','bigint','uuid','text','text','text','timestamptz','transaction_source'],'authenticated',array['EXECUTE'],'money transaction RPC is authenticated');
select function_privs_are('public','create_money_transaction',array['uuid','transaction_type','bigint','uuid','text','text','text','timestamptz','transaction_source'],'anon',array[]::text[],'money transaction RPC rejects anonymous callers');
select ok(public.is_valid_timezone('Asia/Jakarta'),'known timezone accepted');
select ok(not public.is_valid_timezone('Etc/Definitely_Not_A_Zone'),'unknown timezone rejected');
select col_has_check('public','debts','paid_installments','paid installments are constrained');
select col_not_null('public','debts','due_date','debt due date is required');
select has_check('public','debts','debt progress consistency is constrained');
select has_check('public','debts','debt due date consistency is constrained');
select function_privs_are('public','record_debt_payment',array['uuid','bigint','text','timestamptz','integer'],'authenticated',array[]::text[],'legacy debt payment rejects authenticated callers');
select function_privs_are('public','record_debt_payment_v2',array['uuid','uuid','bigint','text','timestamptz','integer','text'],'authenticated',array['EXECUTE'],'account-backed debt payment is authenticated');
select function_privs_are('public','record_debt_payment_v2',array['uuid','uuid','bigint','text','timestamptz','integer','text'],'anon',array[]::text[],'account-backed debt payment rejects anonymous callers');
select function_privs_are('public','update_debt',array['uuid','text','bigint','integer','date','integer'],'authenticated',array['EXECUTE'],'debt metadata update is authenticated');
select function_privs_are('public','update_debt',array['uuid','text','bigint','integer','date','integer'],'anon',array[]::text[],'debt metadata update rejects anonymous callers');
select has_function('public','update_debt',array['uuid','text','bigint','integer','date','integer'],'debt metadata update RPC exists');
select has_table('public','saving_goal_dispositions','saving dispositions table exists');
select row_security_active('public','saving_goal_dispositions','saving dispositions uses RLS');
select table_privs_are('public','saving_goal_dispositions','anon',array[]::text[],'anonymous users cannot read dispositions');
select table_privs_are('public','saving_goal_dispositions','authenticated',array['SELECT'],'users can only read dispositions through RLS');
select function_privs_are('public','use_saving_goal',array['uuid','bigint','uuid','text','text','integer','text'],'authenticated',array['EXECUTE'],'goal usage RPC is authenticated');
select function_privs_are('public','use_saving_goal',array['uuid','bigint','uuid','text','text','integer','text'],'anon',array[]::text[],'goal usage RPC rejects anonymous callers');
select function_privs_are('public','cancel_saving_goal',array['uuid','uuid','integer','text'],'authenticated',array['EXECUTE'],'goal cancellation RPC is authenticated');
select function_privs_are('public','cancel_saving_goal',array['uuid','uuid','integer','text'],'anon',array[]::text[],'goal cancellation RPC rejects anonymous callers');
select function_privs_are('public','get_parser_finance_preview',array['uuid','bigint','transaction_type'],'authenticated',array['EXECUTE'],'parser preview RPC is authenticated');
select function_privs_are('public','create_parser_expense',array['uuid','bigint','text','text','boolean','text'],'authenticated',array['EXECUTE'],'protected expense RPC is authenticated');
select function_privs_are('public','record_salary_income',array['uuid','bigint','text','text','text'],'authenticated',array['EXECUTE'],'salary receipt RPC is authenticated');
select function_privs_are('public','apply_salary_savings',array['uuid','bigint','text','text'],'authenticated',array['EXECUTE'],'salary allocation RPC is authenticated');
select function_privs_are('public','apply_windfall_split',array['uuid','bigint','text','text','jsonb','text'],'authenticated',array['EXECUTE'],'windfall RPC is authenticated');
select function_privs_are('public','apply_windfall_split',array['uuid','bigint','text','text','jsonb','text'],'anon',array[]::text[],'windfall RPC rejects anonymous callers');
select function_privs_are('public','get_salary_budget_reduction_candidate',array['bigint'],'authenticated',array['EXECUTE'],'salary reduction preview is authenticated');
select function_privs_are('public','get_salary_budget_reduction_candidate',array['bigint'],'anon',array[]::text[],'salary reduction preview rejects anonymous callers');
select function_privs_are('public','apply_salary_budget_reduction',array['uuid','integer','bigint','uuid','jsonb','text'],'authenticated',array['EXECUTE'],'salary reduction apply is authenticated');
select function_privs_are('public','apply_salary_budget_reduction',array['uuid','integer','bigint','uuid','jsonb','text'],'anon',array[]::text[],'salary reduction apply rejects anonymous callers');
select function_privs_are('public','preview_saving_goal_deposit',array['uuid','bigint'],'authenticated',array['EXECUTE'],'goal deposit preview is authenticated');
select function_privs_are('public','preview_saving_goal_deposit',array['uuid','bigint'],'anon',array[]::text[],'goal deposit preview rejects anonymous callers');
select function_privs_are('public','apply_saving_goal_deposit',array['uuid','uuid','bigint','uuid','integer','integer','text','text'],'authenticated',array['EXECUTE'],'goal deposit apply is authenticated');
select function_privs_are('public','apply_saving_goal_deposit',array['uuid','uuid','bigint','uuid','integer','integer','text','text'],'anon',array[]::text[],'goal deposit apply rejects anonymous callers');

select * from finish();
rollback;
