import { assertEquals, assertThrows } from 'jsr:@std/assert';
import { canonicalJson, exact, extractProviderJson, isoDate, isoTimestamp, jpegBase64, money, object, oneOf, optionalVersion, routeKey, text, validateParserProvider } from './helpers.ts';

Deno.test('route key normalizes trailing slash',()=>assertEquals(routeKey('get','/api/v1/accounts/'),'GET /api/v1/accounts'));
Deno.test('validators accept valid payload',()=>{const v=object({name:' Cash ',amount:1000,kind:'CASH'});exact(v,['name','amount','kind']);assertEquals(text(v,'name'),'Cash');assertEquals(money(v,'amount'),1000);assertEquals(oneOf(v,'kind',['CASH','BANK'] as const),'CASH');});
Deno.test('validation uses 422 and rejects unknown fields',()=>{for(const fn of [()=>money({amount:1.5},'amount'),()=>money({amount:0},'amount'),()=>exact({name:'x',user_id:'x'},['name'])]){const error=assertThrows(fn);assertEquals((error as {status:number}).status,422);}});
Deno.test('If-Match is strictly quoted and permits budget create-only zero',()=>{assertEquals(optionalVersion(new Request('https://example.test',{headers:{'if-match':'"3"'}})),3);assertEquals(optionalVersion(new Request('https://example.test',{headers:{'if-match':'"0"'}})),0);for(const value of ['3','x','"03"','*'])assertThrows(()=>optionalVersion(new Request('https://example.test',{headers:{'if-match':value}})));});
Deno.test('canonical JSON ignores object key order',()=>assertEquals(canonicalJson({b:2,a:{d:4,c:3}}),canonicalJson({a:{c:3,d:4},b:2})));
Deno.test('provider JSON extraction accepts plain JSON',()=>assertEquals(extractProviderJson('{"intent":"unknown"}'),{intent:'unknown'}));
Deno.test('provider JSON extraction accepts fenced JSON',()=>assertEquals(extractProviderJson('```json\n{"intent":"unknown"}\n```'),{intent:'unknown'}));
Deno.test('ISO validators reject normalized and timezone-less values',()=>{assertEquals(isoDate({date:'2024-02-29'},'date'),'2024-02-29');assertEquals(isoTimestamp({at:'2026-07-22T10:30:00+07:00'},'at'),'2026-07-22T10:30:00+07:00');for(const fn of [()=>isoDate({date:'2024-02-30'},'date'),()=>isoTimestamp({at:'2026-07-22T10:30:00'},'at')])assertThrows(fn);});
Deno.test('provider parser validates and resolves only owned names',()=>{const result=validateParserProvider({intent:'create_expense',confidence:.9,fields:{amount:12000,account_kind:null,account_name:'cash',category_name:'Makan',description:'Nasi',debt_name:null,goal_name:null,new_balance:null},reason:null},[{id:'owned',name:'Cash'}],[{name:'Makan'}]);assertEquals(result.fields.account_id,'owned');assertEquals(result.needs_confirmation,true);assertEquals(validateParserProvider({intent:'unknown',confidence:0,fields:{amount:null,account_kind:null,account_name:'other',category_name:null,description:null,debt_name:null,goal_name:null,new_balance:null},reason:null},[{id:'owned',name:'Cash'}],[]).fields.account_id,null);});
Deno.test('provider parser preserves new account fields',()=>{const result=validateParserProvider({intent:'create_account',confidence:.99,fields:{amount:null,account_kind:'E_WALLET',account_name:'DANA',category_name:null,description:null,debt_name:null,goal_name:null,new_balance:25000},reason:null},[{id:'cash',name:'Cash'}],[]);assertEquals(result.fields.account_id,null);assertEquals(result.fields.account_name,'DANA');assertEquals(result.fields.account_kind,'E_WALLET');});
Deno.test('provider parser rounds decimal rupiah',()=>{const result=validateParserProvider({intent:'set_balance',confidence:.98,fields:{amount:null,account_kind:null,account_name:'Cash',category_name:null,description:'Saldo aktif',debt_name:null,goal_name:null,new_balance:3942785.51},reason:null},[{id:'cash',name:'Cash'}],[]);assertEquals(result.fields.new_balance,3942786);});
Deno.test('provider parser rejects unsafe output',()=>{for(const value of [{intent:'bad',confidence:1,fields:{}},{intent:'unknown',confidence:2,fields:{amount:null,account_kind:null,account_name:null,category_name:null,description:null,debt_name:null,goal_name:null,new_balance:null},reason:null},{intent:'unknown',confidence:0,fields:{amount:Number.MAX_SAFE_INTEGER+1,account_kind:null,account_name:null,category_name:null,description:null,debt_name:null,goal_name:null,new_balance:null},reason:null}])assertThrows(()=>validateParserProvider(value,[],[]));});
Deno.test('JPEG payload validation is bounded',()=>{assertEquals(jpegBase64('/9j/2Q=='),'/9j/2Q==');for(const value of ['iVBORw==','/9j/2Q==junk','/9j/'+ 'A'.repeat(20)])assertThrows(()=>jpegBase64(value,6));});
