import { supabase } from '@/core/lib/supabase';

const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL;
const configuredAnonKey = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY;
if (!supabaseUrl || !configuredAnonKey) throw new Error('Konfigurasi Supabase belum lengkap. Atur EXPO_PUBLIC_SUPABASE_URL dan EXPO_PUBLIC_SUPABASE_ANON_KEY.');
const supabaseAnonKey: string = configuredAnonKey;
const baseUrl = `${supabaseUrl}/functions/v1/api/api/v1`;

export interface ApiMeta { request_id: string }
export interface ApiEnvelope<T> { data: T; meta: ApiMeta }
export interface ApiErrorBody { code: string; message: string; details: { field: string; reason: string }[] }

export class EdgeApiError extends Error {
  constructor(public status: number, public error: ApiErrorBody, public requestId?: string, public retryAfter?: number) {
    super(error.message);
    this.name = 'EdgeApiError';
  }
}

export const isNetworkOrUnavailable = (error: unknown) => error instanceof TypeError || error instanceof EdgeApiError && error.status === 503;
export const idempotencyKey = (scope: string) => `${scope}-${Date.now()}-${Math.random().toString(36).slice(2)}`;

async function request<T>(path: string, options: RequestInit & { version?: number; idempotencyKey?: string } = {}): Promise<ApiEnvelope<T>> {
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) throw new EdgeApiError(401, { code: 'AUTHENTICATION_REQUIRED', message: 'Sesi telah berakhir.', details: [] });
  const requestId = `${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const headers = new Headers(options.headers);
  headers.set('Authorization', `Bearer ${session.access_token}`);
  headers.set('apikey', supabaseAnonKey);
  headers.set('Accept', 'application/json');
  headers.set('X-Request-Id', requestId);
  if (options.body) headers.set('Content-Type', 'application/json');
  if (options.version !== undefined) headers.set('If-Match', `"${options.version}"`);
  if (options.idempotencyKey) headers.set('Idempotency-Key', options.idempotencyKey);
  let response: Response;
  try {
    response = await fetch(`${baseUrl}${path}`, { ...options, headers });
  } catch {
    throw new TypeError('Tidak dapat terhubung ke server.');
  }
  const payload = await response.json().catch(() => null) as ApiEnvelope<T> | { error: ApiErrorBody; meta?: ApiMeta } | null;
  if (!response.ok) {
    const body = payload && 'error' in payload ? payload : null;
    const msg = response.status === 503
      ? 'Layanan sementara tidak tersedia (503 Service Temporarily Unavailable).'
      : body?.error?.message ?? 'Respons server tidak valid.';
    throw new EdgeApiError(response.status, body?.error ?? { code: 'INVALID_RESPONSE', message: msg, details: [] }, body?.meta?.request_id ?? requestId, Number(response.headers.get('retry-after')) || undefined);
  }
  if (!payload || !('data' in payload) || !payload.meta?.request_id) throw new EdgeApiError(502, { code: 'INVALID_RESPONSE', message: 'Respons server tidak valid.', details: [] }, requestId);
  return payload;
}

export interface Resource { id: string; version: number; created_at: string; updated_at: string }
export interface Profile extends Resource { email: string; full_name: string; timezone: string; theme_mode: 'system' | 'light' | 'dark'; cloud_sync_enabled: boolean; avatar_url?: string | null }
export interface Account extends Resource { name: string; kind: 'CASH' | 'BANK' | 'E_WALLET' | 'INVESTMENT'; balance: number; is_default: boolean; account_number: string | null; icon: string | null }
export interface Category extends Resource { name: string; type: 'INCOME' | 'EXPENSE'; icon: string | null; color: string | null }
export interface Budget extends Resource { month: string; total_limit: number; used_amount: number; remaining_amount: number; percent_used: number; day_of_month: number; days_in_month: number; days_left: number }
export interface BudgetCycleSummary { cycle: Resource & { name: string; start_date: string; end_date: string; planned_income: number; minimum_balance: number; savings_target: number; status: 'ACTIVE' | 'CLOSED' }; totals: { operational_balance: number; actual_income: number; expected_income: number; actual_expense: number; allocated: number; unallocated_plan: number; remaining_obligations: number; remaining_flexible: number; safe_to_spend: number; projected_safe_to_spend: number; daily_safe_limit: number }; accounts: Pick<Account, 'id' | 'name' | 'kind' | 'balance'>[]; income_plans: { id: string; name: string; expected_amount: number; expected_date: string; status: 'EXPECTED' | 'RECEIVED' | 'CANCELLED' }[]; allocations: { id: string; kind: 'CATEGORY' | 'OBLIGATION'; category_id: string; category_name: string; color: string | null; label: string; allocated_amount: number; used_amount: number; remaining_amount: number; overspent_amount: number; percent_used: number; due_date: string | null; version: number }[] }
export interface BudgetSetupInput { name: string; start_date: string; end_date: string; planned_income: number; expected_income_date: string; minimum_balance: number; savings_target: number; account_ids: string[]; allocations: { category_id: string; kind: 'CATEGORY' | 'OBLIGATION'; label: string; amount: number; due_date?: string | null; sort_order?: number }[] }
export interface BudgetAllocationEvent { id: string; event_type: 'CREATED' | 'REVISED' | 'TRANSFERRED'; source_allocation_id: string | null; source_label: string | null; destination_allocation_id: string | null; destination_label: string | null; amount: number | null; note: string | null; occurred_at: string }
export interface BudgetPace { allocation_id: string; label: string; kind: 'CATEGORY' | 'OBLIGATION'; expected_percent: number; actual_percent: number; pace_status: 'ON_TRACK' | 'AT_RISK' | 'OVERSPENT'; projected_exhaustion_date: string | null; days_early: number }
export interface SavingGoal extends Resource { name: string; target_amount: number; target_date: string | null; saved_amount: number; remaining_amount: number; progress_percent: number; monthly_needed: number | null; status: string; lifecycle_status: 'ACTIVE' | 'PAUSED' | 'FUNDED' | 'CANCELLED' | 'ARCHIVED'; funded_at: string | null; funding_mode: 'VIRTUAL_LOCK' | 'SEPARATE_ACCOUNT' | null; source_account_id: string | null; savings_account_id: string | null; priority: 'CRITICAL' | 'HIGH' | 'NORMAL' | 'LOW'; recurrence_unit: 'MONTH' | 'YEAR' | null; recurrence_interval: 1 | 3 | 6 | null; current_cycle_start: string | null; current_cycle_end: string | null }
export interface Debt extends Resource { name: string; total_amount: number; paid_amount: number; remaining_amount: number; progress_percent: number; due_date: string | null; status: string; installment_plan: { tenor_months: number; monthly_amount: number; start_date: string; paid_installments: number; months_left: number; projected_payoff_date: string; next_due_date: string | null } }
export interface SavingsRecommendations { capacity: { safe_now: number; projected: number }; goals: { goal_id: string; name: string; priority: SavingGoal['priority']; remaining_amount: number; required_monthly: number | null; safe_contribution: number; projected_safe_contribution: number; expected_funded: number; behind_amount: number; schedule_status: 'FUNDED' | 'OVERDUE' | 'BEHIND' | 'ON_TRACK'; projected_completion_date: string | null }[] }
export interface SavingMutation { id: string; goal_id: string; account_id: string | null; kind: 'DEPOSIT' | 'WITHDRAWAL'; amount: number; note: string | null; occurred_at: string; created_at: string }
export interface DebtPayment { id: string; debt_id: string; account_id: string | null; amount: number; note: string | null; occurred_at: string; created_at: string }
export interface Summary { total_balance: number; total_income_month: number; total_expense_month: number; percentage_change: number | null; remaining_debt: number; recent_transactions: { id: string; type: 'INCOME' | 'EXPENSE'; amount: number; category_name: string | null; description: string | null; occurred_at: string }[] }
export interface AnalyticsOverview { period: '7m'; month_label: string; monthly_buckets: { month: string; label: string; income: number; expense: number; net_savings: number }[]; kpis: { income: number; expense: number; net_savings: number; income_change_percent: number | null; expense_change_percent: number | null }; category_slices: { label: string; amount: number; percentage: number; color: string }[]; quick_stats: { busiest_weekday: string | null; largest_category: string | null; quietest_week: number | null; expense_transaction_count: number }; insight: string | null }
export interface AnalyticsChatResponse { answer: string }
export type ParserIntent = 'create_expense' | 'create_income' | 'transfer_account' | 'create_account' | 'set_balance' | 'create_debt' | 'pay_debt' | 'create_goal' | 'deposit_goal' | 'withdraw_goal' | 'update_last_amount' | 'update_last_account' | 'undo_last' | 'get_summary' | 'unknown';
export interface ParserResponse { intent: ParserIntent; confidence: number; needs_confirmation: boolean; fields: { amount?: number | null; account_id?: string | null; account_name?: string | null; source_account_id?: string | null; source_account_name?: string | null; destination_account_id?: string | null; destination_account_name?: string | null; account_kind?: Account['kind'] | null; category_name?: string | null; description?: string | null; debt_name?: string | null; goal_name?: string | null; new_balance?: number | null }; reason?: string | null }
export interface ReceiptExtraction { merchant: string | null; total: number | null; date: string | null; suggested_category_id: string | null; suggested_category_name: string | null; suggested_account_id: string | null; suggested_account_name: string | null; description: string | null; confidence: number; needs_confirmation: true }
export interface ApiNotification { id: string; kind: 'Penting' | 'Keuangan' | 'Sistem'; title: string; message: string; action: string | null; created_at: string; read: boolean }
export interface NotificationList { items: ApiNotification[]; unread_count: number }
export interface ParserFinancePreview { gross_balance: number; protected_amount: number; free_balance: number; protected_shortfall: number; recovery_impacts: { goal_id: string; name: string; amount: number }[]; goals: WindfallAllocation[]; debts: WindfallAllocation[]; free_remainder: number }
export interface BalanceBreakdown { gross_balance: number; protected_balance: number; free_balance: number }
export interface GoalRecovery { status: 'FUNDED' | 'OVERDUE' | 'UNSCHEDULED' | 'ACTIVE'; required_monthly: number | null; plans: ({ kind: 'CONTRIBUTE'; amount: number | null } | { kind: 'EXTEND'; months: number } | { kind: 'REDUCE_TARGET'; minimum: number })[] }
export interface WindfallAllocation { id: string; name: string; kind: 'GOAL' | 'DEBT'; version: number; maximum: number; recommended: number }
export interface SalaryReceipt { transaction_id: string; planned_amount: number; safe_amount: number }
export interface BudgetReductionCandidate { id: string; label: string; version: number; remaining: number; reducible: number }
export interface GoalDepositPreview { accepted_amount: number; overflow_amount: number; destinations: Pick<SavingGoal, 'id' | 'name' | 'version' | 'remaining_amount'>[] }

const json = (body: unknown) => JSON.stringify(body);
export const edgeApi = {
  getProfile: () => request<Profile>('/me/profile'),
  updateProfile: (body: Partial<Pick<Profile, 'full_name' | 'timezone' | 'theme_mode' | 'cloud_sync_enabled'>>, version: number) => request<Profile>('/me/profile', { method: 'PATCH', body: json(body), version }),
  reset: () => request<{ status: 'reset'; reset_at: string }>('/me/data', { method: 'DELETE', body: json({ confirmation: 'RESET' }) }),
  registerPushToken: (token: string, platform: 'android' | 'ios') => request<{ status: 'registered' }>('/me/push-tokens', { method: 'POST', body: json({ token, platform }), idempotencyKey: `push-${token}` }),
  unregisterPushToken: (token: string) => request<{ status: 'unregistered' }>('/me/push-tokens', { method: 'DELETE', body: json({ token }) }),
  sendTestPush: () => request<{ status: 'sent'; tickets: number }>('/me/push-test', { method: 'POST', idempotencyKey: idempotencyKey('push-test') }),
  accounts: () => request<Account[]>('/accounts'),
  createAccount: (body: { name: string; kind?: Account['kind']; opening_balance?: number; is_default?: boolean; account_number?: string | null; icon?: string | null }, key: string) => request<Account>('/accounts', { method: 'POST', body: json(body), idempotencyKey: key }),
  updateAccount: (id: string, body: Pick<Account, 'name' | 'kind' | 'is_default' | 'account_number' | 'icon'>, version: number) => request<Account>(`/accounts/${encodeURIComponent(id)}`, { method: 'PATCH', body: json(body), version }),
  setAccountBalance: (id: string, balance: number, version: number, key: string) => request<Account>(`/accounts/${encodeURIComponent(id)}/balance`, { method: 'POST', body: json({ balance }), version, idempotencyKey: key }),
  transferAccount: async (sourceId: string, destinationId: string, amount: number, note?: string | null) => { const { data, error } = await supabase.rpc('transfer_between_accounts', { p_source_id: sourceId, p_destination_id: destinationId, p_amount: amount, p_note: note ?? null, p_occurred_at: null }); if (error) throw new Error(error.message === 'INSUFFICIENT_BALANCE' ? 'Saldo akun sumber tidak mencukupi.' : error.message === 'SOURCE_NOT_FOUND' || error.message === 'DESTINATION_NOT_FOUND' ? 'Akun transfer tidak ditemukan. Muat ulang lalu coba lagi.' : 'Transfer gagal. Coba lagi.'); return data as string; },
  deleteAccount: (id: string, version: number) => request<{ status: 'deleted' }>(`/accounts/${encodeURIComponent(id)}`, { method: 'DELETE', version }),
  categories: () => request<Category[]>('/categories'),
  createCategory: (body: { name: string; type?: Category['type'] }, key: string) => request<Category>('/categories', { method: 'POST', body: json(body), idempotencyKey: key }),
  updateCategory: (id: string, name: string, version: number) => request<Category>(`/categories/${encodeURIComponent(id)}`, { method: 'PATCH', body: json({ name }), version }),
  deleteCategory: (id: string, version: number) => request<{ status: 'deleted' }>(`/categories/${encodeURIComponent(id)}`, { method: 'DELETE', version }),
  budget: () => request<Budget | null>('/budgets/current'),
  upsertBudget: (total_limit: number, version?: number) => request<Budget>('/budgets/current', { method: 'PUT', body: json({ total_limit }), version: version ?? 0 }),
  budgetCycle: async () => { const { data, error } = await supabase.rpc('get_budget_cycle_summary', { p_cycle_id: null }); if (error) throw error; return data as BudgetCycleSummary | null; },
  setupBudgetCycle: async (input: BudgetSetupInput) => { const { data, error } = await supabase.rpc('setup_budget_cycle_v2', { p_name: input.name, p_start_date: input.start_date, p_end_date: input.end_date, p_planned_income: input.planned_income, p_expected_income_date: input.expected_income_date, p_minimum_balance: input.minimum_balance, p_savings_target: input.savings_target, p_account_ids: input.account_ids, p_allocations: input.allocations }); if (error) throw new Error(error.message === 'INVALID_BUDGET_ACCOUNTS' ? 'Pilih minimal satu akun operasional.' : error.message); return data as string; },
  transferBudgetAllocation: async (input: { source_id: string; destination_id: string; amount: number; source_version: number; destination_version: number; note?: string | null }) => { const { data, error } = await supabase.rpc('transfer_budget_allocation', { p_source_id: input.source_id, p_destination_id: input.destination_id, p_amount: input.amount, p_source_version: input.source_version, p_destination_version: input.destination_version, p_note: input.note ?? null }); if (error) throw error; return data as string; },
  budgetAllocationHistory: async (cycleId: string) => { const { data, error } = await supabase.rpc('get_budget_allocation_history', { p_cycle_id: cycleId }); if (error) throw error; return data as BudgetAllocationEvent[]; },
  budgetPace: async (cycleId: string) => { const { data, error } = await supabase.rpc('get_budget_pace', { p_cycle_id: cycleId }); if (error) throw error; return data as BudgetPace[]; },
  closeBudgetCycle: async (cycleId: string) => { const { data, error } = await supabase.rpc('close_budget_cycle', { p_cycle_id: cycleId }); if (error) throw new Error(error.message === 'ACTIVE_BUDGET_NOT_FOUND' ? 'Budget aktif tidak ditemukan.' : 'Gagal menutup periode budget.'); return data as string; },
  goals: () => request<SavingGoal[]>('/saving-goals'),
  savingsRecommendations: async () => { const { data, error } = await supabase.rpc('get_savings_recommendations'); if (error) throw error; return data as SavingsRecommendations; },
  createGoal: async (body: { name: string; target_amount: number; target_date?: string | null; recurrence_unit?: 'MONTH' | 'YEAR' | null; recurrence_interval?: 1 | 3 | 6 | null; initial_amount?: number; funding_mode?: 'VIRTUAL_LOCK' | 'SEPARATE_ACCOUNT'; source_account_id?: string; savings_account_id?: string | null }, key: string) => { const { data, error } = await supabase.rpc('create_funded_saving_goal', { p_name: body.name, p_target_amount: body.target_amount, p_target_date: body.target_date ?? null, p_recurrence_unit: body.recurrence_unit ?? null, p_recurrence_interval: body.recurrence_interval ?? null, p_initial_amount: body.initial_amount ?? 0, p_funding_mode: body.funding_mode ?? null, p_source_account_id: body.source_account_id ?? null, p_savings_account_id: body.savings_account_id ?? null, p_operation_key: key }); if (error) throw new Error(error.message); return data as SavingGoal; },
  updateGoal: async (id: string, body: { name: string; target_amount: number; target_date?: string | null; recurrence_unit?: 'MONTH' | 'YEAR' | null; recurrence_interval?: 1 | 3 | 6 | null }, version: number) => { const { data, error } = await supabase.rpc('upsert_saving_goal', { p_goal_id: id, p_name: body.name, p_target_amount: body.target_amount, p_target_date: body.target_date ?? null, p_recurrence_unit: body.recurrence_unit ?? null, p_recurrence_interval: body.recurrence_interval ?? null, p_expected_version: version }); if (error) throw new Error(error.message === 'TARGET_BELOW_SAVED' ? 'Target tidak boleh lebih kecil dari dana terkumpul.' : error.message); return data as SavingGoal; },
  deleteGoal: (id: string, version: number) => request<{ status: 'deleted' }>(`/saving-goals/${encodeURIComponent(id)}`, { method: 'DELETE', version }),
  goalMutations: (id: string) => request<SavingMutation[]>(`/saving-goals/${encodeURIComponent(id)}/mutations`),
  configureGoal: async (id: string, input: { funding_mode: 'VIRTUAL_LOCK' | 'SEPARATE_ACCOUNT'; source_account_id: string; savings_account_id?: string | null; priority: SavingGoal['priority'] }, version: number) => { const { data, error } = await supabase.rpc('configure_saving_goal', { p_goal_id: id, p_mode: input.funding_mode, p_source_account_id: input.source_account_id, p_savings_account_id: input.savings_account_id ?? null, p_priority: input.priority, p_expected_version: version }); if (error) throw new Error(error.message); return data as SavingGoal; },
  setGoalPaused: async (id: string, paused: boolean, version: number) => { const { data, error } = await supabase.rpc('set_saving_goal_paused', { p_goal_id: id, p_paused: paused, p_expected_version: version }); if (error) throw new Error(error.message); return data as SavingGoal; },
  reallocateGoal: async (source: SavingGoal, destination: SavingGoal, amount: number, key: string) => { const { data, error } = await supabase.rpc('reallocate_saving_goal', { p_source_goal_id: source.id, p_destination_goal_id: destination.id, p_amount: amount, p_source_version: source.version, p_destination_version: destination.version, p_operation_key: key }); if (error) throw new Error(error.message === 'INCOMPATIBLE_FUNDING_LOCATION' ? 'Realokasi hanya tersedia untuk goal dengan lokasi dana yang sama.' : error.message); return data as string; },
  useGoal: async (goal: SavingGoal, input: { amount: number; category_id: string; description?: string | null; note?: string | null; surplus_choice: 'KEEP' | 'REDIRECT' | 'RELEASE'; redirect_goal?: SavingGoal | null }, key: string) => { const { data, error } = await supabase.rpc('use_saving_goal_v2', { p_goal_id: goal.id, p_amount: input.amount, p_category_id: input.category_id, p_description: input.description ?? null, p_note: input.note ?? null, p_surplus_choice: input.surplus_choice, p_redirect_goal_id: input.redirect_goal?.id ?? null, p_expected_version: goal.version, p_redirect_version: input.redirect_goal?.version ?? null, p_operation_key: key }); if (error) throw new Error(error.message); return data; },
  cancelGoalWithRelease: async (goal: SavingGoal, destinationAccountId: string, key: string) => { const { data, error } = await supabase.rpc('cancel_saving_goal', { p_goal_id: goal.id, p_destination_account_id: destinationAccountId, p_expected_version: goal.version, p_operation_key: key }); if (error) throw new Error(error.message); return data as SavingGoal; },
  createGoalMutation: async (id: string, body: { account_id: string; kind: SavingMutation['kind']; amount: number; note?: string | null; occurred_at?: string }, version: number, key: string) => { const { data, error } = await supabase.rpc('record_saving_goal_mutation_v3', { p_goal_id: id, p_account_id: body.account_id, p_kind: body.kind, p_amount: body.amount, p_note: body.note ?? null, p_expected_version: version, p_operation_key: key }); if (error) throw new Error(error.message === 'INSUFFICIENT_AVAILABLE_BALANCE' ? 'Saldo bebas akun tidak mencukupi karena sebagian dana terlindungi.' : error.message === 'GOAL_NOT_CONFIGURED' ? 'Pilih metode penyimpanan goal terlebih dahulu.' : error.message); return data as SavingMutation; },
  goalDepositPreview: async (goalId: string, amount: number) => { const { data, error } = await supabase.rpc('preview_saving_goal_deposit', { p_goal_id: goalId, p_amount: amount }); if (error) throw new Error(error.message); return data as GoalDepositPreview; },
  applyGoalDeposit: async (input: { goal: SavingGoal; account_id: string; amount: number; redirect_goal: SavingGoal | null; note?: string | null }, key: string) => { const { data, error } = await supabase.rpc('apply_saving_goal_deposit', { p_goal_id: input.goal.id, p_account_id: input.account_id, p_amount: input.amount, p_redirect_goal_id: input.redirect_goal?.id ?? null, p_expected_version: input.goal.version, p_redirect_version: input.redirect_goal?.version ?? null, p_note: input.note ?? null, p_operation_key: key }); if (error) throw new Error(error.message); return data as { accepted_amount: number; redirected_amount: number }; },
  debts: () => request<Debt[]>('/debts'),
  createDebt: (body: { name: string; total_amount: number; tenor_months: number; paid_installments: number; start_date: string }, key: string) => request<Debt>('/debts', { method: 'POST', body: json(body), idempotencyKey: key }),
  updateDebt: (id: string, body: { name: string; total_amount: number; tenor_months: number; start_date: string }, version: number) => request<Debt>(`/debts/${encodeURIComponent(id)}`, { method: 'PATCH', body: json(body), version }),
  deleteDebt: (id: string, version: number) => request<{ status: 'deleted' }>(`/debts/${encodeURIComponent(id)}`, { method: 'DELETE', version }),
  debtPayments: (id: string) => request<DebtPayment[]>(`/debts/${encodeURIComponent(id)}/payments`),
  createDebtPayment: async (id: string, body: { account_id: string; amount: number; note?: string | null; occurred_at?: string }, version: number, key: string) => { const { data, error } = await supabase.rpc('record_debt_payment_v2', { p_debt_id: id, p_account_id: body.account_id, p_amount: body.amount, p_note: body.note ?? null, p_occurred_at: body.occurred_at ?? null, p_expected_version: version, p_operation_key: key }); if (error) throw new Error(error.message === 'INSUFFICIENT_BALANCE' ? 'Saldo akun tidak mencukupi.' : error.message === 'PAYMENT_EXCEEDS_REMAINING' ? 'Pembayaran melebihi sisa utang.' : error.message); return data as DebtPayment; },
  createTransaction: (body: { type: 'INCOME' | 'EXPENSE'; amount: number; account_id: string; category_name?: string | null; description?: string | null; note?: string | null; occurred_at?: string; source?: 'MANUAL' | 'PARSER' | 'RECEIPT' }, key: string) => request<unknown>('/transactions', { method: 'POST', body: json(body), idempotencyKey: key }),
  parserFinancePreview: async (accountId: string, amount: number, type: 'INCOME' | 'EXPENSE') => { const { data, error } = await supabase.rpc('get_parser_finance_preview', { p_account_id: accountId, p_amount: amount, p_type: type }); if (error) throw new Error(error.message); return data as ParserFinancePreview; },
  balanceBreakdown: async () => { const { data, error } = await supabase.rpc('get_balance_breakdown'); if (error) throw new Error(error.message); return data as BalanceBreakdown; },
  goalRecovery: async (id: string) => { const { data, error } = await supabase.rpc('get_saving_goal_recovery', { p_goal_id: id }); if (error) throw new Error(error.message); return data as GoalRecovery; },
  confirmGoalRecovery: async (goal: SavingGoal, key: string) => { const { data, error } = await supabase.rpc('confirm_four_month_recovery', { p_goal_id: goal.id, p_expected_version: goal.version, p_operation_key: key }); if (error) throw new Error(error.message); return data as { months: 4; monthly_amount: number }; },
  resetGoalCycle: async (goal: SavingGoal, key: string) => { const { data, error } = await supabase.rpc('reset_saving_goal_cycle', { p_goal_id: goal.id, p_expected_version: goal.version, p_operation_key: key }); if (error) throw new Error(error.message); return data; },
  createParserExpense: async (input: { account_id: string; amount: number; category_name?: string | null; description?: string | null; override_protected: boolean }, key: string) => { const { data, error } = await supabase.rpc('create_parser_expense', { p_account_id: input.account_id, p_amount: input.amount, p_category_name: input.category_name ?? null, p_description: input.description ?? null, p_override_protected: input.override_protected, p_operation_key: key }); if (error) throw new Error(error.message === 'PROTECTED_FUNDS_CONFIRMATION_REQUIRED' ? 'Konfirmasi penggunaan dana terlindungi.' : error.message); return data; },
  recordSalaryIncome: async (input: { account_id: string; amount: number; category_name?: string | null; description?: string | null }, key: string) => { const { data, error } = await supabase.rpc('record_salary_income', { p_account_id: input.account_id, p_amount: input.amount, p_category_name: input.category_name ?? null, p_description: input.description ?? null, p_operation_key: key }); if (error) throw new Error(error.message); return data as SalaryReceipt; },
  salaryBudgetCandidate: async (amount: number) => { const { data, error } = await supabase.rpc('get_salary_budget_reduction_candidate', { p_amount: amount }); if (error) throw new Error(error.message); return data as BudgetReductionCandidate | null; },
  applySalaryBudgetReduction: async (input: { allocation: BudgetReductionCandidate; amount: number; account_id: string; goals: { id: string; version: number; amount: number }[] }, key: string) => { const { data, error } = await supabase.rpc('apply_salary_budget_reduction', { p_allocation_id: input.allocation.id, p_expected_version: input.allocation.version, p_amount: input.amount, p_account_id: input.account_id, p_goals: input.goals, p_operation_key: key }); if (error) throw new Error(error.message); return data; },
  applySalarySavings: async (accountId: string, amount: number, choice: 'PLANNED' | 'SAFE' | 'SKIP', key: string) => { const { data, error } = await supabase.rpc('apply_salary_savings', { p_account_id: accountId, p_amount: amount, p_choice: choice, p_operation_key: key }); if (error) throw new Error(error.message); return data as { applied: number; remainder?: number }; },
  applyWindfallSplit: async (input: { account_id: string; amount: number; category_name?: string | null; description?: string | null; allocations: { id: string; kind: WindfallAllocation['kind']; amount: number }[] }, key: string) => { const { data, error } = await supabase.rpc('apply_windfall_split', { p_account_id: input.account_id, p_amount: input.amount, p_category_name: input.category_name ?? null, p_description: input.description ?? null, p_allocations: input.allocations, p_operation_key: key }); if (error) throw new Error(error.message); return data as { transaction_id: string; allocated: number; free_remainder: number }; },
  summary: () => request<Summary>('/summary'),
  analytics: (period: '7m' | '3m' | '1m' = '7m') => request<AnalyticsOverview>(`/analytics/overview?period=${period}`),
  analyticsChat: (question: string) => request<AnalyticsChatResponse>('/analytics/chat', { method: 'POST', body: json({ question }), idempotencyKey: idempotencyKey('analytics-chat') }),
  parseInput: (input: string) => request<ParserResponse>('/parser', { method: 'POST', body: json({ input }) }),
  parseImage: (image_base64: string) => request<ParserResponse>('/parser/image', { method: 'POST', body: json({ image_base64 }) }),
  notifications: () => request<NotificationList>('/notifications'),
  markNotificationRead: (id: string) => request<{ status: 'read' }>(`/notifications/${encodeURIComponent(id)}/read`, { method: 'POST' }),
  markAllNotificationsRead: () => request<{ status: 'read'; count: number }>('/notifications/read-all', { method: 'POST' }),
  extractReceipt: (body: { image_uri: string }) => request<ReceiptExtraction>('/receipts/extractions', { method: 'POST', body: json(body), idempotencyKey: idempotencyKey('receipt') }),
};
