create type public.saving_funding_mode as enum('VIRTUAL_LOCK','SEPARATE_ACCOUNT');
alter table public.saving_goals add column funding_mode public.saving_funding_mode,add column source_account_id uuid,add column savings_account_id uuid,add column priority text not null default 'NORMAL' check(priority in('CRITICAL','HIGH','NORMAL','LOW'));
alter table public.saving_goals add foreign key(source_account_id,user_id) references public.accounts(id,user_id),add foreign key(savings_account_id,user_id) references public.accounts(id,user_id),add check(source_account_id is null or savings_account_id is null or source_account_id<>savings_account_id);
create index saving_goals_source_user_idx on public.saving_goals(source_account_id,user_id) where source_account_id is not null;
create index saving_goals_savings_user_idx on public.saving_goals(savings_account_id,user_id) where savings_account_id is not null;
create table public.saving_virtual_locks(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,goal_id uuid not null,account_id uuid not null,locked_amount bigint not null check(locked_amount>0),version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(goal_id),foreign key(goal_id,user_id) references public.saving_goals(id,user_id) on delete cascade,foreign key(account_id,user_id) references public.accounts(id,user_id));
create index saving_virtual_locks_user_idx on public.saving_virtual_locks(user_id);
create index saving_virtual_locks_account_user_idx on public.saving_virtual_locks(account_id,user_id);
create trigger saving_virtual_locks_updated before update on public.saving_virtual_locks for each row execute function public.set_updated_at();
alter table public.saving_virtual_locks enable row level security;
create policy saving_virtual_locks_read on public.saving_virtual_locks for select to authenticated using((select auth.uid())=user_id);
revoke all on public.saving_virtual_locks from anon,authenticated; grant select on public.saving_virtual_locks to authenticated;

create function public.get_account_locked_amount(p_account_id uuid) returns bigint language sql security definer set search_path='' stable as $$ select coalesce(sum(locked_amount),0)::bigint from public.saving_virtual_locks where account_id=p_account_id and user_id=(select auth.uid()) $$;
create function public.configure_saving_goal(p_goal_id uuid,p_mode public.saving_funding_mode,p_source_account_id uuid,p_savings_account_id uuid,p_priority text,p_expected_version integer) returns public.saving_goals language plpgsql security definer set search_path='' as $$ declare u uuid:=auth.uid(); g public.saving_goals; begin if u is null then raise exception 'AUTH_REQUIRED' using errcode='P0001'; end if; if p_priority not in('CRITICAL','HIGH','NORMAL','LOW') then raise exception 'INVALID_PRIORITY' using errcode='P0001'; end if; select * into g from public.saving_goals where id=p_goal_id and user_id=u and deleted_at is null for update; if not found then raise exception 'GOAL_NOT_FOUND' using errcode='P0001'; end if; if g.version<>p_expected_version then raise exception 'VERSION_CONFLICT' using errcode='P0001'; end if; if p_mode='VIRTUAL_LOCK' and p_source_account_id is null or p_mode='SEPARATE_ACCOUNT' and (p_source_account_id is null or p_savings_account_id is null or p_source_account_id=p_savings_account_id) then raise exception 'INVALID_FUNDING_ACCOUNTS' using errcode='P0001'; end if; if not exists(select 1 from public.accounts where id=p_source_account_id and user_id=u and deleted_at is null) or p_savings_account_id is not null and not exists(select 1 from public.accounts where id=p_savings_account_id and user_id=u and deleted_at is null) then raise exception 'ACCOUNT_NOT_FOUND' using errcode='P0001'; end if; update public.saving_goals set funding_mode=p_mode,source_account_id=p_source_account_id,savings_account_id=case when p_mode='SEPARATE_ACCOUNT' then p_savings_account_id else null end,priority=p_priority where id=g.id returning * into g; return g; end $$;

create function public.record_saving_goal_mutation_v3(p_goal_id uuid,p_account_id uuid,p_kind public.saving_mutation_kind,p_amount bigint,p_note text,p_expected_version integer,p_operation_key text) returns public.saving_goal_mutations language plpgsql security definer set search_path='' as $$ declare u uuid:=auth.uid(); g public.saving_goals; src public.accounts; dst public.accounts; m public.saving_goal_mutations; l public.saving_virtual_locks; locked bigint; transfer_id uuid; next_saved bigint; begin if u is null then raise exception 'AUTH_REQUIRED' using errcode='P0001'; end if; select * into m from public.saving_goal_mutations where user_id=u and operation_key=p_operation_key; if found then return m; end if; select * into g from public.saving_goals where id=p_goal_id and user_id=u and deleted_at is null for update; if not found or g.funding_mode is null then raise exception 'GOAL_NOT_CONFIGURED' using errcode='P0001'; end if; if g.version<>p_expected_version then raise exception 'VERSION_CONFLICT' using errcode='P0001'; end if; next_saved:=case when p_kind='DEPOSIT' then g.saved_amount+p_amount else g.saved_amount-p_amount end; if p_amount<1 or next_saved<0 or next_saved>g.target_amount then raise exception 'INVALID_GOAL_BALANCE' using errcode='P0001'; end if;
 if g.funding_mode='VIRTUAL_LOCK' then select * into src from public.accounts where id=g.source_account_id and user_id=u and deleted_at is null for update; select * into l from public.saving_virtual_locks where goal_id=g.id for update; if p_kind='DEPOSIT' then select coalesce(sum(locked_amount),0) into locked from public.saving_virtual_locks where account_id=src.id; if src.balance-locked<p_amount then raise exception 'INSUFFICIENT_AVAILABLE_BALANCE' using errcode='P0001'; end if; if l.id is null then insert into public.saving_virtual_locks(user_id,goal_id,account_id,locked_amount) values(u,g.id,src.id,p_amount); else update public.saving_virtual_locks set locked_amount=locked_amount+p_amount where id=l.id; end if; else if l.id is null or l.locked_amount<p_amount then raise exception 'INSUFFICIENT_LOCK' using errcode='P0001'; end if; if l.locked_amount=p_amount then delete from public.saving_virtual_locks where id=l.id; else update public.saving_virtual_locks set locked_amount=locked_amount-p_amount where id=l.id; end if; end if;
 else perform 1 from public.accounts where id in(g.savings_account_id,p_account_id) and user_id=u and deleted_at is null order by id for update; if p_kind='DEPOSIT' then select * into src from public.accounts where id=p_account_id and user_id=u and deleted_at is null; select * into dst from public.accounts where id=g.savings_account_id and user_id=u and deleted_at is null; else select * into src from public.accounts where id=g.savings_account_id and user_id=u and deleted_at is null; select * into dst from public.accounts where id=p_account_id and user_id=u and deleted_at is null; end if; select coalesce(sum(locked_amount),0) into locked from public.saving_virtual_locks where account_id=src.id; if src.balance-locked<p_amount then raise exception 'INSUFFICIENT_AVAILABLE_BALANCE' using errcode='P0001'; end if; update public.accounts set balance=balance-p_amount where id=src.id; update public.accounts set balance=balance+p_amount where id=dst.id; insert into public.account_transfers(user_id,source_account_id,destination_account_id,amount,note) values(u,src.id,dst.id,p_amount,'Tabungan: '||g.name) returning id into transfer_id; end if;
 insert into public.saving_goal_mutations(user_id,goal_id,account_id,operation_key,kind,amount,note) values(u,g.id,p_account_id,p_operation_key,p_kind,p_amount,nullif(btrim(p_note),'')) returning * into m; update public.saving_goals set saved_amount=next_saved where id=g.id; return m; end $$;

revoke execute on function public.get_account_locked_amount(uuid),public.configure_saving_goal(uuid,public.saving_funding_mode,uuid,uuid,text,integer),public.record_saving_goal_mutation_v3(uuid,uuid,public.saving_mutation_kind,bigint,text,integer,text) from public,anon;
grant execute on function public.get_account_locked_amount(uuid),public.configure_saving_goal(uuid,public.saving_funding_mode,uuid,uuid,text,integer),public.record_saving_goal_mutation_v3(uuid,uuid,public.saving_mutation_kind,bigint,text,integer,text) to authenticated;
